#ifndef DICEPARSER_GLOBAL_H
#define DICEPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DICEPARSER_LIBRARY)
#define DICEPARSER_EXPORT Q_DECL_EXPORT
#else
#define DICEPARSER_EXPORT Q_DECL_IMPORT
#endif
#endif // DICEPARSER_GLOBAL_H
