#ifndef DICEPARSER_QOBJECT_GLOBAL_H
#define DICEPARSER_QOBJECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DICEPARSER_QOBJECT_LIBRARY)
#define DICEPARSER_QOBJECT_EXPORT Q_DECL_EXPORT
#else
#define DICEPARSER_QOBJECT_EXPORT Q_DECL_IMPORT
#endif
#endif // DICEPARSER_QOBJECT_GLOBAL_H
